### ISSUE TITLE
Support for different models

### ISSUE THREAD

**Issue by adayNU** [mkwatson/chat_any_site#1]
Would it be possible to allow the user to specify which LLM they'd like to use as an argument? I.e.

```sh
chatanysite \
  --open-api-key=<your openai api key> \
  --site=https://langchain.readthedocs.io/sitemap.xml
  --model_name=gpt-3.5-turbo
```

Maybe even down the road support something like `--model_provider=Anthropic`

**Comment by mkwatson** [comment]
It's already done. And I `git commit --amend --no-edit` and `git push --force-with-lease` because I can.

**Comment by adayNU** [comment]
Awesome. Great work.
